/*
 * Kaldi speach recognition REST API
 * Simple REST interface for posting tasks for non realtime speach recognition
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.mvshyvk.kaldi.service.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;

/**
 * Segment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2020-04-23T21:31:33.644Z[GMT]")
public class Segment {
	@JsonProperty("timeStart")
	private int timeStart = 0; // in milliseconds

	@JsonProperty("timeEnd")
	private int timeEnd = 0; // in milliseconds

	@JsonProperty("segmentText")
	private String segmentText = null;

	public Segment timeStart(int timeStart) {
		this.timeStart = timeStart;
		return this;
	}

	/**
	 * Get timeStart
	 * 
	 * @return timeStart
	 **/
	@JsonProperty("timeStart")
	@Schema(example = "21642", required = true, description = "")
	@NotNull
	public int getTimeStart() {
		return timeStart;
	}

	public void setTimeStart(int timeStart) {
		this.timeStart = timeStart;
	}

	public Segment timeEnd(int timeEnd) {
		this.timeEnd = timeEnd;
		return this;
	}

	/**
	 * Get timeEnd
	 * 
	 * @return timeEnd
	 **/
	@JsonProperty("timeEnd")
	@Schema(example = "36374", description = "")
	public int getTimeEnd() {
		return timeEnd;
	}

	public void setTimeEnd(int timeEnd) {
		this.timeEnd = timeEnd;
	}

	public Segment segmentText(String segmentText) {
		this.segmentText = segmentText;
		return this;
	}

	/**
	 * Get segmentText
	 * 
	 * @return segmentText
	 **/
	@JsonProperty("segmentText")
	@Schema(example = "from a wave file", required = true, description = "")
	@NotNull
	public String getSegmentText() {
		return segmentText;
	}

	public void setSegmentText(String segmentText) {
		this.segmentText = segmentText;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Segment segment = (Segment) o;
		return Objects.equals(this.timeStart, segment.timeStart) && Objects.equals(this.timeEnd, segment.timeEnd)
				&& Objects.equals(this.segmentText, segment.segmentText);
	}

	@Override
	public int hashCode() {
		return Objects.hash(timeStart, timeEnd, segmentText);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Segment {\n");

		sb.append("    timeStart: ").append(toIndentedString(timeStart)).append("\n");
		sb.append("    timeEnd: ").append(toIndentedString(timeEnd)).append("\n");
		sb.append("    segmentText: ").append(toIndentedString(segmentText)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
